FOS/Controllers/DmsController.cs
using Document_Management.Data;
using Document_Management.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;

namespace Document_Management.Controllers
{
    public class DmsController : Controller
    {
        private readonly IWebHostEnvironment _hostingEnvironment;

        //Database Context
        private readonly ApplicationDbContext _dbcontext;

        //Passing the dbcontext in to another variable
        public DmsController(IWebHostEnvironment hostingEnvironment, ApplicationDbContext context)
        {
            _hostingEnvironment = hostingEnvironment;
            _dbcontext = context;
        }

        //Get for the Action Dms/Upload
        [HttpGet]
        public IActionResult UploadFile()
        {
            var username = HttpContext.Session.GetString("username");
            if (!string.IsNullOrEmpty(username))
            {
                return View(new FileDocument());
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        [HttpPost]
        public IActionResult UploadFile(FileDocument fileDocument, IFormFile file)
        {
            try
            {
                if (ModelState.IsValid && file != null && file.Length > 0)
                {
                    var username = HttpContext.Session.GetString("username");

                    if (string.IsNullOrEmpty(username))
                    {
                        return RedirectToAction("Login", "Account");
                    }

                    fileDocument.DateUploaded = DateTime.Now;
                    fileDocument.Username = username;

                    var filename = Path.GetFileName(file.FileName);
                    var uniquePart = $"{fileDocument.Department}_{fileDocument.DateUploaded:yyyyMMddHHmmssfff}";
                    filename = $"{uniquePart}_{filename}"; // Combine uniquePart with the original filename

                    // Determine the subdirectory based on the selected department
                    var departmentSubdirectory = Path.Combine("Files", fileDocument.Department);

                    // Combine the subdirectory with the web root path
                    var uploadFolderPath = Path.Combine(_hostingEnvironment.WebRootPath, departmentSubdirectory);

                    // Ensure the department-specific subdirectory exists
                    if (!Directory.Exists(uploadFolderPath))
                    {
                        Directory.CreateDirectory(uploadFolderPath);
                    }

                    var filePath = Path.Combine(uploadFolderPath, filename);

                    using (var stream = new FileStream(filePath, FileMode.Create))
                    {
                        file.CopyTo(stream); // Copy the file to the server
                    }

                    fileDocument.Name = filename;
                    fileDocument.Location = filePath;
                    _dbcontext.FileDocuments.Add(fileDocument);

                    //Implementing the logs
                    LogsModel logs = new(username, $"Upload new file in {fileDocument.Department} Department");
                    _dbcontext.Logs.Add(logs);

                    _dbcontext.SaveChanges();

                    TempData["success"] = "File uploaded successfully";

                    return RedirectToAction("UploadFile");
                }
                else
                {
                    TempData["error"] = "Please fill out all the required data.";
                }
            }
            catch (Exception ex)
            {
                TempData["error"] = "Contact MIS: " + ex.Message;
            }

            return View(fileDocument);
        }

        //[HttpGet]
        //public async Task<IActionResult> DownloadFile(int? page)
        //{
        //    int pageSize = 10; // Number of items per page
        //    int pageIndex = page ?? 1; // Default to page 1 if no page number is specified

        //    // Retrieve the files from the database and project them into FileViewModel
        //    var fileViewModels = _dbcontext.FileDocuments
        //        .Select(file => new FileDocument
        //        {
        //            Name = file.Name,
        //            Location = file.Location,
        //            DateUploaded = file.DateUploaded,
        //            Description = file.Description,
        //            Department = file.Department
        //        })
        //        .OrderBy(u => u.Department);

        //    var model = await PaginatedList<FileDocument>.CreateAsync(fileViewModels, pageIndex, pageSize);

        //    return View(model);
        //}

        public IActionResult DownloadFile()
        {
            var username = HttpContext.Session.GetString("username");
            if (string.IsNullOrEmpty(username))
            {
                return RedirectToAction("Login", "Account");
            }

            var wwwrootPath = Path.Combine(_hostingEnvironment.WebRootPath, "Files");
            var folders = Directory.GetDirectories(wwwrootPath).Select(Path.GetFileName);
            return View(folders);
        }

        public async Task<IActionResult> DisplayFiles(string folderName)
        {
            ViewData["folderName"] = folderName; // Using ViewData

            // Retrieve the user's department from the session or any other method you're using
            var userAccessFolders = HttpContext.Session.GetString("useraccessfolders");

            // Split the userDepartment string into individual department names
            var userDepartments = userAccessFolders.Split(',');

            // Check if any of the user's departments allow access to the specified folderName
            if (!userDepartments.Any(dep => dep.Trim() == folderName))
            {
                TempData["Denied"] = "You have no access to this action. Please contact the MIS Department if you think this is a mistake.";
                return RedirectToAction("DownloadFile"); // Redirect to the login page or another appropriate action
            }

            //// If any of the user's departments are allowed, continue with your code to display files
            //int pageSize = 10; // Number of items per page
            //int pageIndex = page ?? 1; // Default to page 1 if no page number is specified

            var wwwrootPath = Path.Combine(_hostingEnvironment.WebRootPath, "Files");
            var folderPath = Path.Combine(wwwrootPath, folderName); // wwwroot/Files/null
            var pdfFiles = Directory.GetFiles(folderPath, "*.pdf").Select(Path.GetFileName);

            // Assuming you have a list of FileDocument objects in your database
            // You can filter them based on folderName and select the relevant properties
            var fileDocuments = await _dbcontext.FileDocuments
                .Where(file => file.Department == folderName && pdfFiles.Contains(file.Name))
                .Select(file => new FileDocument
                {
                    Name = file.Name,
                    Location = file.Location,
                    DateUploaded = file.DateUploaded,
                    Description = file.Description,
                    Department = file.Department,
                    Username = file.Username
                })
                .OrderByDescending(u => u.DateUploaded).ToListAsync();

            //var model = await PaginatedList<FileDocument>.CreateAsync(fileDocuments, pageIndex, pageSize);

            return View(fileDocuments);
        }
    }
}

FOS/Controllers/GatepassController.cs
using Document_Management.Data;
using Document_Management.Hubs;
using Document_Management.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;
using System.Text;

namespace Document_Management.Controllers
{
    
    public class GatepassController : Controller
    {
        //public IActionResult Index()
        //{
        //    return View();
        //}

        //Database Context
        private readonly ApplicationDbContext _dbcontext;
        private readonly IHubContext<NotificationHub> _notificationHub;

        //Passing the dbcontext in to another variable
        public GatepassController(ApplicationDbContext context, IHubContext<NotificationHub> notification)
        {
            _dbcontext = context;
            _notificationHub = notification;
        }

        //RequestGatepass
        [HttpGet]
        public IActionResult Insert()
        {
            var username = HttpContext.Session.GetString("username");
            if (!string.IsNullOrEmpty(username))
            {
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        [HttpPost]
        public async Task<IActionResult> Insert(RequestGP gpInfo)
        {
            var username = HttpContext.Session.GetString("username");

            if (ModelState.IsValid)
            {
                if (username != null)
                {
                    gpInfo.Username = username;
                }
                _dbcontext.Gatepass.Add(gpInfo);
                _dbcontext.SaveChanges();
                TempData["success"] = "Request created successfully";
                var hubConnections = _dbcontext.HubConnections.Where(h => h.Username == "leo").ToList();
                foreach (var hubConnection in hubConnections)
                {
                    await _notificationHub.Clients.Client(hubConnection.ConnectionId).SendAsync("ReceivedPersonalNotification", "You have a new request", gpInfo.Username);
                }
                return RedirectToAction("Insert");
            }

            return View(gpInfo);
        }

        public IActionResult Validator()
        {
            var username = HttpContext.Session.GetString("userrole")?.ToLower();
            if (!(username == "validator"))
            {
                TempData["ErrorMessage"] = "You have no access to this action. Please contact the MIS Department if you think this is a mistake.";
                return RedirectToAction("Privacy", "Home"); // Redirect to the login page or another appropriate action
            }

          
            ViewBag.users = _dbcontext.Gatepass.ToList();

            return View();
        }

        [HttpGet]
        public IActionResult Approved(int? id)
        {
            var requestGP = _dbcontext.Gatepass.FirstOrDefault(x => x.Id == id);

            if (requestGP == null)
            {
                return NotFound();
            }

            return View(requestGP);
        }

        [HttpPost, ActionName("Approved")]
        public async Task<IActionResult> Approved(int id)
        {
            if (_dbcontext.Gatepass == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Account'  is null.");
            }
            var client = await _dbcontext.Gatepass.FindAsync(id);
            //if (client != null)
            //{
            //    _dbcontext.Gatepass.Remove(client);
            //}

            if (client != null)
            {
                client.Status = "Approved";
                await _dbcontext.SaveChangesAsync();
                TempData["success"] = "Approved successfully";
                var hubConnections = _dbcontext.HubConnections.Where(h => h.Username == client.Username).ToList();
                foreach (var hubConnection in hubConnections)
                {
                    await _notificationHub.Clients.Client(hubConnection.ConnectionId).SendAsync("ReceivedPersonalNotification", "Your request has been approved", client.Username);
                }
            }
            return RedirectToAction(nameof(Validator));
        }

        [HttpGet]
        public IActionResult Disapproved(int? id)
        {
            var requestGP = _dbcontext.Gatepass.FirstOrDefault(x => x.Id == id);

            if (requestGP == null)
            {
                return NotFound();
            }

            return View(requestGP);
        }

        [HttpPost, ActionName("Disapproved")]
        public async Task<IActionResult> Disapproved(int id)
        {
            if (_dbcontext.Gatepass == null)
            {
                return Problem("Entity set 'ApplicationDbContext.Account'  is null.");
            }
            var client = await _dbcontext.Gatepass.FindAsync(id);
            //if (client != null)
            //{
            //    _dbcontext.Gatepass.Remove(client);
            //}

            if (client != null)
            {
                client.Status = "Disapproved";
                await _dbcontext.SaveChangesAsync();
                TempData["success"] = "Disapproved successfully";
                var hubConnections = _dbcontext.HubConnections.Where(h => h.Username == client.Username).ToList();
                foreach (var hubConnection in hubConnections)
                {
                    await _notificationHub.Clients.Client(hubConnection.ConnectionId).SendAsync("ReceivedPersonalNotification", "Your request has been disapproved", client.Username);
                }
            }
            return RedirectToAction(nameof(Validator));
        }

        [HttpGet]
        public IActionResult RecievedGP()
        {
            var username = HttpContext.Session.GetString("username");

            if (!string.IsNullOrEmpty(username))
            {
                ViewBag.users = _dbcontext.Gatepass.ToList();
                return View();
            }
            else
            {
                return RedirectToAction("Login", "Account");
            }
        }

        [HttpGet]
        public IActionResult Generate(int id)
        {
            var requestGP = _dbcontext.Gatepass.FirstOrDefault(x => x.Id == id);

            if (requestGP == null)
            {
                return NotFound();
            }

            return View(requestGP);
        }
    }
}

FOS/Controllers/LogsController.cs
using Document_Management.Data;
using Document_Management.Models;
using Microsoft.AspNetCore.Mvc;

namespace Document_Management.Controllers
{
    public class LogsController : Controller
    {
        //Database Context
        private readonly ApplicationDbContext _dbcontext;

        //Passing the dbcontext in to another variable
        public LogsController(ApplicationDbContext context)
        {
            _dbcontext = context;
        }

        public IActionResult Index()
        {
            var userrole = HttpContext.Session.GetString("userrole");

            if (userrole != "Admin")
            {
                TempData["ErrorMessage"] = "You have no access to this action. Please contact the MIS Department if you think this is a mistake.";
                return RedirectToAction("Privacy", "Home"); // Redirect to the login page or another appropriate action
            }

            //int pageSize = 10; // Number of items per page
            //int pageIndex = page ?? 1; // Default to page 1 if no page number is specified

            var logs = _dbcontext.Logs
                .OrderByDescending(u => u.Date)
                .ToList();

            //var model = await PaginatedList<LogsModel>.CreateAsync(logs, pageIndex, pageSize);

            return View(logs);
        }
    }
}

FOS/Views/Shared/_Layout.cshtml
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] | Filpride Online System</title>
   @*  <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" /> *@
    <link href="~/F O S.ico" rel="shortcut icon" type="image/x-icon" />
    <link rel="stylesheet" href="~/css/site.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DocumentManagement.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.css">
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.6/css/jquery.dataTables.css" />

</head>
<body>
    <header>
        @* <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DocumentManagement</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AppRoles" asp-action="Index">Roles</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
            <partial name="_LoginPartial" />
        </nav> *@
        <nav class="navbar navbar-expand-lg bg-primary" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" asp-controller="Home" asp-action="Index">F O S</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01" aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarColor01">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">
                                Home
                                <span class="visually-hidden">(current)</span>
                            </a>
                        </li>
                        @* <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="AppRoles" asp-action="Index">Roles</a>
                        </li> *@
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Index">Employees</a>
                        </li>
                      
                        <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Gatepass</a>
                        <div class="dropdown-menu">
                               
                                <a class="dropdown-item" asp-controller="Gatepass" asp-action="Insert">Request Gatepass</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Gatepass" asp-action="Validator">Validator</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Gatepass" asp-action="RecievedGP">Recieved Gatepass</a>
                     @*    <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Separated link</a> *@
                        </div>
                        </li> 

                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Document Management</a>
                            <div class="dropdown-menu">

                                <a class="dropdown-item" asp-controller="Dms" asp-action="UploadFile">Upload File</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" asp-controller="Dms" asp-action="DownloadFile">Download File</a>
                            </div>
                        </li>
                        @{
                            var userrole = Context.Session.GetString("userrole")?.ToLower();                          
                        }
                        @if (userrole == "admin")
                        {
                            <li class="nav-item">
                                <a class="nav-link" asp-area="" asp-controller="Logs" asp-action="Index">Logs</a>
                            </li>
                        }
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="ChatDemo">Chat Demo</a>
                        </li>
                        @*   <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        </li> *@
                       @*  <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li> *@
                       @*  <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Dropdown</a>
                            <div class="dropdown-menu">
                                <a class="dropdown-item" href="#">Action</a>
                                <a class="dropdown-item" href="#">Another action</a>
                                <a class="dropdown-item" href="#">Something else here</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Separated link</a>
                            </div>
                        </li> *@
                    </ul>
                   @*  <form class="d-flex">
                        <input class="form-control me-sm-2" type="search" placeholder="Search">
                        <button class="btn btn-secondary my-2 my-sm-0" type="submit">Search</button>
                    </form> *@
                    <partial name="_LoginPartial" /> 
                </div>             
            </div>
            
        </nav>
    </header>
    <div class="container">
        <main role="main" class="py-3">
            <input type="hidden" id="hfUsername" value="@HttpContextAccessor.HttpContext?.Session.GetString("username")" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Filpride Online Systems - <a asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <!-- Add this link in your HTML to include SweetAlert2 -->
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@10"></script>
    <script src="~/lib/microsoft/signalr/dist/browser/signalr.js"></script>
    <script src="~/js/notification.js"></script>
    <script src="https://cdn.datatables.net/1.13.6/js/jquery.dataTables.js"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

FOS/Views/Shared/_Notification.cshtml
@if(TempData["success"] != null)
{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/lib/query/dist/jquery.min.js"></script>
    <script>
        Swal.fire(
            'Success',
            '@TempData["success"]',
            'success'
        )
    </script>
}

@if (TempData["error"] != null)
{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/lib/query/dist/jquery.min.js"></script>
    <script>
        Swal.fire(
            'Error',
            '@TempData["error"]',
            'error'
        )
    </script>

}

@if (TempData["Denied"] != null)
{
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/lib/query/dist/jquery.min.js"></script>
    <script>
        Swal.fire(
            'Oops...',
            '@TempData["Denied"]',
            'error'
        )
    </script>

}